[files]
extend-exclude = [
    "/tests/screenshot.test.ts-snapshots/screenshot-ai-protection-budget-contro-dark-chromium-linux.png",
    "/tests/screenshot.test.ts-snapshots/screenshot-ai-protection-budget-contro-light-chromium-linux.png"
]