name: Typos Spell Check

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  CLICOLOR: 1

jobs:
  typos:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88
        with:
          toolchain: 1.96.1
          targets: x86_64-unknown-linux-musl
      - name: Install Typos-CLI
        run: cargo install --git https://github.com/crate-ci/typos.git --rev bb4666ad77b539a6b4ce4eda7ebb6de553704021
      - name: Spell Check Repo
        run: typos
